// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeStatus } from "./MergeStatus";

export type TaskPrStatus = { task_id: string, has_open_pr: boolean, open_pr_url: string | null, latest_pr_status: MergeStatus | null, latest_pr_url: string | null, };
